### ISSUE TITLE
Found a bug

### ISSUE THREAD

**Issue by Leo-U** [ChrisAntley1/Speech-to-Text-Lichess#20]
When I tried to capture a piece with my knight, it threw the "more than 1 piece of this type has access to destination square" error in the console. However, I had only one knight attacking that square. I realized that it was the enemy knight that was also attacking that square.

screenshot: https://i.imgur.com/shyVANk.png

link to the match: https://lichess.org/il9DHkMx7eKs

**Comment by ChrisAntley1** [comment]
Great catch. When boardstate.js was checking which of user's Knights was in range of a destination square, it was missing 1 particular case. Any knight that was 1 square away and on the same row or column would incorrectly get returned as in-range of the destination (able to jump to that square). Which is obviously wrong!

![KnightBug](https://user-images.githubusercontent.com/77400072/136655778-a1d9bce5-911c-432c-95da-6103ec7e3f0d.png)

The missing logic that seems to fix the issue:

![image](https://user-images.githubusercontent.com/77400072/136656149-d46f1613-86ea-456d-aae6-245aa44d45c5.png)

Updated on the chrome web store, it should get approved and released within a few days.

**Comment by Leo-U** [comment]
Yeah, I looked at my screenshot this morning and realized I was likely completely wrong about the problem. Anyway, great program, thank you for your efforts
