### ISSUE TITLE
Language of Speech Recognition API

### ISSUE THREAD

**Issue by achojoao** [ChrisAntley1/Speech-to-Text-Lichess#21]
Hey @ChrisAntley1 , amazing job with this plugin! So useful!

This is more a feature request than an issue. 

I've been looking the source code and I've realised that you are hardcoding the value of the language for the speech recognition API:

`recognition.lang = 'en-US';`

Could it be possible to read the language from the browser? Something like:

`recognition.lang = navigator.language || navigator.userLanguage;`

Or maybe, it's a better idea to add an option in the plugin's configuration UI to let the user set the language, being the default language `en-US`.

Please, let me know which option you prefer and if you have time to do the modifications or if you accept Pull Requests to do it by myself.

Good Game!

**Comment by ChrisAntley1** [comment]
Hi @achojoao, glad you're liking it.

 When I wrote this extension, the voice processing service would always ignore any Speech Grammar settings. It actually seemed to interpret multiple languages properly when tested regardless.

Have you tried or had success using the app in your preferred language?

That said, I will go ahead and have it acquire the browser's language instead, probably a good idea in case anything changes with Speech Grammar in the future!

**Comment by ChrisAntley1** [comment]
I see that it's a separate value from the grammar object altogether, so I've already put my foot in my mouth, haha.

Made the change to release_build and published on Chrome Web Store.

**Comment by achojoao** [comment]
Works like a charm! Now it detects "caballo", "torre" and so on.

Thanks @ChrisAntley1 !
